"""Models module for ZipTax SDK."""

from .responses import (
    CartItemRefundWithTaxRequest,
    CartItemRefundWithTaxResponse,
    CartItemWithTax,
    CartItemWithTaxResponse,
    CreateOrderRequest,
    Currency,
    CurrencyResponse,
    Exemption,
    JurisdictionName,
    JurisdictionType,
    OrderResponse,
    RefundTax,
    RefundTransactionRequest,
    RefundTransactionResponse,
    Tax,
    TaxCloudAddress,
    TaxCloudAddressResponse,
    TaxType,
    UpdateOrderRequest,
    V60AccountMetrics,
    V60AddressDetail,
    V60BaseRate,
    V60DisplayRate,
    V60Metadata,
    V60PostalCodeAddressDetail,
    V60PostalCodeResponse,
    V60PostalCodeResult,
    V60Response,
    V60ResponseInfo,
    V60Service,
    V60Shipping,
    V60SourcingRules,
    V60TaxSummary,
)

__all__ = [
    # V60 Models
    "V60Response",
    "V60ResponseInfo",
    "V60Metadata",
    "V60BaseRate",
    "V60Service",
    "V60Shipping",
    "V60SourcingRules",
    "V60TaxSummary",
    "V60DisplayRate",
    "V60AddressDetail",
    "V60AccountMetrics",
    "V60PostalCodeResponse",
    "V60PostalCodeResult",
    "V60PostalCodeAddressDetail",
    "JurisdictionType",
    "JurisdictionName",
    "TaxType",
    # TaxCloud Models
    "TaxCloudAddress",
    "TaxCloudAddressResponse",
    "Tax",
    "RefundTax",
    "Currency",
    "CurrencyResponse",
    "Exemption",
    "CartItemWithTax",
    "CartItemWithTaxResponse",
    "CreateOrderRequest",
    "OrderResponse",
    "UpdateOrderRequest",
    "CartItemRefundWithTaxRequest",
    "CartItemRefundWithTaxResponse",
    "RefundTransactionRequest",
    "RefundTransactionResponse",
]
